# Generated by Django 4.0.3 on 2022-04-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('grade', models.PositiveIntegerField()),
                ('mailid', models.CharField(max_length=200)),
                ('contactnumber', models.CharField(max_length=60)),
                ('adharnumber', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('vaccinationstatus', models.CharField(max_length=60)),
            ],
        ),
    ]
